name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform (Dev)
        run: terraform apply -auto-approve
        env:
          TF_VAR_environment: dev

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=YOUR_PROJECT_KEY
            -Dsonar.organization=YOUR_ORGANIZATION
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Approval for QA
        uses: chriskinsman/github-action-pause@v1.0.0

      - name: Apply Terraform (QA)
        run: terraform apply -auto-approve
        env:
          TF_VAR_environment: qa

      - name: Approval for UAT
        uses: chriskinsman/github-action-pause@v1.0.0

      - name: Apply Terraform (UAT)
        run: terraform apply -auto-approve
        env:
          TF_VAR_environment: uat

      - name: Approval for Prod
        uses: chriskinsman/github-action-pause@v1.0.0

      - name: Apply Terraform (Prod)
        run: terraform apply -auto-approve
        env:
          TF_VAR_environment: prod
